### ISSUE TITLE
Do not use cxd4-rsp as the default RSP plugin

### ISSUE THREAD

**Issue by Yersho** [Rosalie241/BetterMajorasMaskInstaller#11]
While more accurate for LLE, cxd4-rsp usually causes more issues for casual users who just want HLE graphics with their HD texture pack. Since the whole point of this installer is to set up Project 64 for this texture pack, it would be better for users to just simply use the default RSP plugin that comes with Project 64 for HLE graphics.

**Comment by Rosalie241** [comment]
considering cxd4's rsp plugin is set to HLE mode by default, this is unrequired.
