### ISSUE TITLE
Fails downloading Project64: Cannot find artifact containing "Win32" in the filename

### ISSUE THREAD

**Issue by vaindil** [Rosalie241/BetterMajorasMaskInstaller#14]
Tried to use this just now, and it fails during the Project64 download step with the below error. I'm on Windows 10 x64.

```
Downloading Project64...
Downloading Project64 Failed
Cannot find artifact containing "Win32" in the filename
   at BetterMajorasMaskInstaller.ComponentDownloader.AppVeyorUrlInfo(UrlInfo urlInfo)
   at BetterMajorasMaskInstaller.ComponentDownloader.DownloadComponent(InstallerComponent& component, String directory)
```

**Comment by Rosalie241** [comment]
Fixed with https://github.com/Rosalie241/BetterMajorasMaskInstaller/commit/75611645d3f5401360ef89706e76dcba9d449f7a

[download the new release here](https://github.com/Rosalie241/BetterMajorasMaskInstaller/releases/tag/3.5.0)

Thank you for reporting the breakage! :heart:

**Comment by vaindil** [comment]
Thanks for the quick fix!
