### ISSUE TITLE
Include ParaLLEl RDP

### ISSUE THREAD

**Issue by RibShark** [Rosalie241/BetterMajorasMaskInstaller#16]
https://github.com/mudlord/pj64-parallelrdp

Should work a lot faster than Angrylion RDP Plus with extra enhancements such as upscaling too.

**Comment by Rosalie241** [comment]
Done

![image](https://user-images.githubusercontent.com/18737914/125859537-7c901b66-8fa4-4a11-a61c-2d3975d2ae7d.png)
