### ISSUE TITLE
Linux builds

### ISSUE THREAD

**Issue by pjalsGit** [Rosalie241/BetterMajorasMaskInstaller#19]
You can switch Project64 with Mupen64 and building C# on Linux is possible because of Mono.

**Comment by Rosalie241** [comment]
no, this installer wasn't made with linux in mind and won't ever support linux, I'm not even going to attempt a port.

You can try using my mupen64plus GUI: https://github.com/Rosalie241/RMG which does have a linux version, though setting up a texture pack is still a manual process, but that isn't terribly difficult regardless.
