### ISSUE TITLE
Unknown Memory Action - Emulation Stopped

### ISSUE THREAD

**Issue by ponchoa** [Rosalie241/BetterMajorasMaskInstaller#27]
Hi, thanks for this installer. Unfortunately, I can't make it work right now...
I tried on a fresh install of Project64, and the game runs without any issue, but it doesn't work on the install made from this version :
![image](https://user-images.githubusercontent.com/18310491/187284244-2d990da4-0ff1-42b2-bfcd-86fc75cb2eb3.png)

I tried fiddling with the options everywhere, it's my third reinstall, and nothing changes.
I checked the closed issues, found similar problems that were fixed, but it didn't work for me. (I'm using the latest release.)

Here's the log :
`2022/08/29 21:39:50.286 04572,Error,Exception Handler,CMipsMemoryVM::FilterX86Exception,Invalid memory address: 201C0005`
`2022/08/29 21:39:50.286 04572,Error,User Interface,CNotificationImp::DisplayError,Unknown memory action`
`Emulation stopped`

I tried the patched and unpatched roms, none work, but they do in vanilla Project64.

Here are my plugins :
![image](https://user-images.githubusercontent.com/18310491/187285213-1b90da18-628c-42d5-9579-bf3397af21d9.png)

And my settings :
![image](https://user-images.githubusercontent.com/18310491/187288086-3176ca00-a943-4cc8-9220-9d6cb7e4b733.png)
![image](https://user-images.githubusercontent.com/18310491/187288017-bc8cfdff-7c1e-43a8-8f95-c08f2f7afab5.png)

I have no clue what to do, and a couple of hours of Googling didn't solve my issue.

Thanks for taking the time to read all that ! ^^

**Comment by GhostlyDark** [comment]
Change to the default PJ64 audio plugin.

**Comment by ponchoa** [comment]
Actually, I tried using a different PJ64 nightly build, an older one, and it worked. The most recent one seems to be bugged ! :D
